const functions = require("firebase-functions");
const express = require("express");
const bodyParser = require("body-parser");
const cors = require("cors");
const app = express();
require("./config");
const admin = require("firebase-admin");
const FieldValue = admin.firestore.FieldValue;
const categorySearchController = require("./controllers/categorySearch");
const restaurantController = require("./controllers/restaurant");
const chefPairRecommendationController = require("./controllers/chefPairRecommendation");
const dealsController = require("./controllers/deals");
const userController = require("./controllers/userCreation");
const featuredRestaurantsController = require("./controllers/featuredRestaurants");
const orderController = require("./controllers/order");
const paymentController = require("./controllers/payment");
const reviewsController = require("./controllers/rating");
const verifyPhone = require("./controllers/verifyPhone");
const menuController = require("./controllers/menu");
const updateUserController = require("./controllers/updateUser");
const deleteUserController = require("./controllers/deleteUser");
const qrcodeController = require("./controllers/qrcode");
const tableController = require("./controllers/table");
const otpController = require("./controllers/otp");
const restaurantRouter = require("./routes/restaurant");
const categoryRouter = require("./routes/category");
const variantRouter = require("./routes/variant");
const cartRouter = require("./routes/cart");
const pairingRouter = require("./routes/pairing");
const orderRouter = require("./routes/order");
const paymentRouter = require("./routes/payment");
const menuRouter = require("./routes/menu");
const tableRouter = require("./routes/table");
const ratingRouter = require("./routes/rating");
const ambianceRouter = require("./routes/ambiance");
const cuisineRouter = require("./routes/cuisineType");
const campaignRouter = require("./routes/campaign");
const recommendationRouter = require("./routes/recommendation");
const customClaimRouter = require("./routes/customClaim");
const modifierRouter = require("./routes/modifiers");
const userRouter = require("./routes/user");
const { offer: offerCahnge, router: offerRouter } = require("./routes/offer");
const db = admin.firestore();

app.use(cors({ origin: true }));
app.use(bodyParser.urlencoded({ extended: true }));
app.use(express.json());

app.use("/restaurants", restaurantController(db));
app.use("/search", categorySearchController(db));
app.use("/chefpairrecommendation", chefPairRecommendationController(db));
app.use("/deals", dealsController(db));

exports.api = functions.https.onRequest(app);
exports.featuredrestaurants = functions.https.onRequest(
  featuredRestaurantsController(db)
);
exports.orders = functions.https.onRequest(orderController(db, FieldValue));
exports.table = functions.https.onRequest(tableController(db));
exports.payments = functions.https.onRequest(paymentController(db, FieldValue));
exports.reviews = functions.https.onRequest(reviewsController(db));
exports.verifyPhone = functions.https.onRequest(verifyPhone(db));
exports.menu = functions.https.onRequest(menuController(db));
exports.qrcode = functions.https.onRequest(qrcodeController(db));
exports.otp = functions.https.onRequest(otpController(db));
exports.userCreation = userController(db);
exports.updateUser = functions.https.onRequest(updateUserController(db, admin));
exports.deleteUser = deleteUserController(db);
exports.restaurants = functions.https.onRequest(restaurantRouter);
exports.categories = functions.https.onRequest(categoryRouter);
exports.variants = functions.https.onRequest(variantRouter);
exports.cart = functions.https.onRequest(cartRouter);
exports.pairings = functions.https.onRequest(pairingRouter);
exports.order = functions.https.onRequest(orderRouter);
exports.payment = functions.https.onRequest(paymentRouter);
exports.offer = functions.https.onRequest(offerRouter);
exports.restaurantmenu = functions.https.onRequest(menuRouter);
exports.tables = functions.https.onRequest(tableRouter);
exports.rating = functions.https.onRequest(ratingRouter);
exports.ambiance = functions.https.onRequest(ambianceRouter);
exports.cuisine = functions.https.onRequest(cuisineRouter);
exports.campaigns = functions.https.onRequest(campaignRouter);
exports.recommendations = functions.https.onRequest(recommendationRouter);
exports.customclaims = functions.https.onRequest(customClaimRouter);
exports.modifiers = functions.https.onRequest(modifierRouter);
exports.users = functions.https.onRequest(userRouter);
exports.offerWrite = functions.firestore
  .document("offers/{offer_id}")
  .onWrite(offerCahnge);
